name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Build and test (go ${{ matrix.go }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.25' ]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ^${{ matrix.go }}
        id: go
      - name: CI
        run: go test -v ./...
      - name: Run tests under race detector
        run: go test -v ./... -race

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  ci:
    name: CI Success
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
